services:
  - type: web
    name: promekan
    env: python
    buildCommand: |
      pip install -r requirements.txt
      python manage.py collectstatic --noinput
    startCommand: gunicorn promekan.wsgi:application
    staticPublishPath: staticfiles
