services:
  - type: web
    name: promekan
    env: python
    buildCommand: |
      pip install -r requirements.txt
      python manage.py collectstatic --noinput
    startCommand: |
      python3 manage.py migrate &&
      gunicorn promekan.wsgi:application
      
    staticPublishPath: staticfiles
    envVars:
      - key: DJANGO_SETTINGS_MODULE
        value: promekan.settings
      - key: PYTHONUNBUFFERED
        value: "1"
      - key: CLOUDINARY_CLOUD_NAME
        value: dmj3mhgcg
      - key: CLOUDINARY_API_KEY
        value: 935452695498895
      - key: CLOUDINARY_API_SECRET
        value: fWQvFD-UZXK4VMgR1P43buF6jlE

