# Generated by Django 4.2.20 on 2025-04-12 18:06

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('main', '0003_contactmessage_phone_alter_contactmessage_subject'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='contactmessage',
            name='is_approved',
        ),
        migrations.AlterField(
            model_name='contactmessage',
            name='phone',
            field=models.CharField(blank=True, default='', max_length=20),
            preserve_default=False,
        ),
        migrations.AlterField(
            model_name='contactmessage',
            name='subject',
            field=models.CharField(blank=True, max_length=200),
        ),
    ]
